export const PlantActionTypes = {
  FETCH_PLANTS_START: "FETCH_PLANTS_START",
  FETCH_PLANTS_SUCCESS: "FETCH_PLANTS_SUCCESS",
  FETCH_PLANTS_FAILURE: "FETCH_PLANTS_FAILURE",
  SELECT_PLANTS_TO_WATER: "SELECT_PLANTS_TO_WATER",
  FINISH_WATERING_PLANTS: "FINISH_WATERING_PLANTS",
  WATER_PLANTS: "WATER_PLANTS",
};
